language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - RELEASE_ON_VER=3.5

install:
  - pip install jq yq twine

script:
  - set -e
  - ./pkg-build.sh ./build ./src
  - ./pkg-test.sh ./build ./src
  - ./pkg-release.sh ./build ./src