language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - RELEASE_ON_VER=3.5

install:
    - pip install -r ./src/requirements.txt
    - pip install --upgrade twine

script:
  - set -e
  - python ./src/test.py
  - ./release.sh